In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [54]:
print(torch.__version__)
!nvidia-smi

2.8.0+cu128
Wed Apr  1 17:03:43 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.09              Driver Version: 580.82.09      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5080        Off |   00000000:02:00.0  On |                  N/A |
|  0%   34C    P8             24W /  360W |    1387MiB /  16303MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------

In [16]:
tensor = torch.rand(2,3,4)
tensor

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


tensor([[[0.2350, 0.5909, 0.5939, 0.9286],
         [0.8782, 0.5825, 0.5227, 0.9091],
         [0.6972, 0.6264, 0.3059, 0.4860]],

        [[0.6755, 0.4386, 0.0566, 0.4939],
         [0.5762, 0.1654, 0.1517, 0.9801],
         [0.1147, 0.4527, 0.0898, 0.8586]]])

In [19]:
#create a  random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(3,224,224) # color channels / height / width
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# zeros and ones

In [24]:
shape=(2,3,)

zeros = torch.zeros(shape)
zeros

ones=torch.ones(shape)
ones,ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

# torch.arange(start,end,step)

In [5]:
#create a range of tensors and tensors-like

# torch.arange(start,end,step)
one_to_ten=torch.arange(start=1,end=11,step=1)

# create tensors-like
zeros_like=torch.zeros_like(one_to_ten)

one_to_ten,zeros_like

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

# dtype / shape / device

**Note:** Tensor datatypes is one of the  3 big issues with PyTorch & deep learning
1.right datatype 
2.right shape
3.right device


In [12]:
# Tensor datatypes
float_16_tensor= torch.tensor(torch.rand(1,2,3),
                              dtype=torch.float16, # 32-bit/64-bit floating point(e.g. float 16 / float 32(float) / float 64(double))
                              device="cuda", # (e.g. cuda) ,cpu is default
                              requires_grad=False)


float_64_tensor=float_16_tensor.type(torch.double)
float_16_tensor.dtype,float_64_tensor.dtype,float_16_tensor

print(f"Shape of tensor: {float_16_tensor.shape}")
print(f"Datatype of tensor: {float_16_tensor.dtype}")
print(f"Device tensor is stored on: {float_16_tensor.device}")

Shape of tensor: torch.Size([1, 2, 3])
Datatype of tensor: torch.float16
Device tensor is stored on: cuda:0


/tmp/ipykernel_19419/4002343405.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  float_16_tensor= torch.tensor(torch.rand(1,2,3),


# cpu vs cuda

**Check if GPU is available**
torch.cuda.is_available()

In [ ]:
import time

print("=" * 60)
print("CPU vs GPU ")
print("=" * 60)

# Check if GPU is available
has_cuda = torch.cuda.is_available()
if has_cuda:
    print(f"GPU available: {torch.cuda.get_device_name(0)}")
print()

# ============================================================
# 1. CPU DEVICE (explicit)
# ============================================================
print("1. CPU DEVICE (explicit):")
cpu_tensor = torch.tensor([1, 2, 3],
                          device="cpu")

print(f"   Tensor: {cpu_tensor}")
print(f"   Device: {cpu_tensor.device}")
print()
# ============================================================
# 2. GPU DEVICE (if available)
# ============================================================
if has_cuda:
    print("2. GPU DEVICE:")
    gpu_tensor = torch.tensor([1, 2, 3],
                              device="cuda")
    
    print(f"   Tensor: {gpu_tensor}")
    print(f"   Device: {gpu_tensor.device}")
    
    # Also can use device index (if multiple GPUs)
    gpu_0 = torch.tensor([1, 2, 3],
                         device="cuda:0")  # First GPU
    print(f"   GPU:0 tensor: {gpu_0.device}")
    print()

else:
    print("2. GPU DEVICE: NOT AVAILABLE")

# ============================================================
# 3. Performance comparison (matrix multiplication)
# ============================================================
print("3. PERFORMANCE COMPARISON:")
size = 10000

# CPU computation
cpu_a = torch.randn(size, size, device="cpu")
cpu_b = torch.randn(size, size, device="cpu")

start = time.time()
cpu_result = torch.mm(cpu_a, cpu_b)
cpu_time = time.time() - start
print(f"   CPU time: {cpu_time:.3f} seconds")

if has_cuda:
    # GPU computation
    gpu_a = torch.randn(size, size, device="cuda")
    gpu_b = torch.randn(size, size, device="cuda")
    
    # Warm up GPU
    torch.mm(gpu_a, gpu_b)
    
    start = time.time()
    gpu_result = torch.mm(gpu_a, gpu_b)
    
    gpu_time = time.time() - start
    print(f"   GPU time: {gpu_time:.3f} seconds")
    print(f"   Speedup: {cpu_time / gpu_time:.1f}x faster on GPU")

print("\n✅ Done!")

# Manipulating Tensors
**Matrix multiplication**

# matmul vs loop

In [26]:
%%time
tensor=torch.arange(0,1000,1)
value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
    
torch.matmul(tensor,tensor)

CPU times: user 315 µs, sys: 0 ns, total: 315 µs
Wall time: 436 µs


tensor(332833500)

In [40]:
x=torch.rand(4,4)
x
x[1,2]=-99.0
x,x.argmin()

(tensor([[ 2.7475e-01,  6.4655e-01,  3.4978e-01,  8.3750e-01],
         [ 3.0318e-01,  6.0887e-01, -9.9000e+01,  3.7655e-01],
         [ 4.8299e-01,  2.4932e-01,  4.8366e-01,  6.4104e-01],
         [ 5.1617e-03,  6.8301e-01,  3.9819e-01,  6.7138e-01]]),
 tensor(6))

# Dimensions,axis,slices

# squeeze
# unsqueeze
# torch.permute:https://docs.pytorch.org/docs/stable/generated/torch.permute.html
    torch.permute(input, dims)

In [55]:
# squeeze
x=torch.rand(1,2,3,1,2,3)
x_sq=x.squeeze()
x,x.shape,x_sq,x_sq.shape

# unsqueeze
x_sq_usq=x_sq.unsqueeze(dim=1)
x_sq_usq.shape

# torch.permute
x_random=torch.rand(3,2,1)
x_random,torch.permute(x_random,[2,1,0])

x_permuted=x_random.permute(2,0,1)
x_random,x_permuted

(tensor([[[0.6846],
          [0.7009]],
 
         [[0.3443],
          [0.4023]],
 
         [[0.1112],
          [0.1191]]]),
 tensor([[[0.6846, 0.7009],
          [0.3443, 0.4023],
          [0.1112, 0.1191]]]),
 tensor([[[0.6846],
          [0.7009]],
 
         [[0.3443],
          [0.4023]],
 
         [[0.1112],
          [0.1191]]]))

# indexing

In [56]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
x[0].shape,x[0][0].shape,x[0][0][0].shape

(torch.Size([3, 3]), torch.Size([3]), torch.Size([]))

In [63]:
x[0],x[0][1],x[0][1][2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([4, 5, 6]),
 tensor(6))